Make latte continue running even if cluster_name failed to be read
The following error may happen having some specific cluster conditions:

  scylla::transport::load_balancing::default \
    Datacenter specified as the preferred one (eu-north-1) does not exist! \
      error: Cassandra error: Failed to execute query \
        "SELECT cluster_name, release_version FROM system.local" \
          with params []: Protocol Error: Empty query plan - driver bug!

So, this is not critical, much more valueable to continue a test run
with a main stress load.

So, catch error if it happens, print it out as warning and continue
with 'unknown' value as a cluster name.